### DISCUSSION TITLE
Missing some Features

### DISCUSSION THREAD

**Discussion by evwerkz** [OFFLINE-GmbH/oc-boxes-support#108] [Ideas and feature requests]
I'm missing an upload form by repeater. Mediafinder form works but i need title and description functions for images.
I try it to extend this: 

```php
\OFFLINE\Boxes\Models\Box::extend(function ($model){
            $model->hasMany = [
                'repeater_block' => [
                    \RepeaterBlock::class,
                    'key' => 'parent_id',
                    'delete' => true
                ],
            ];
        });
```

Doc: https://docs.octobercms.com/3.x/element/form/widget-repeater.html#example-of-using-related-records
But it dost work.

--

Settings to allow adding limited same box.
Occasionally I want to allow a box only once per page.

--

The page templates are very cool. But I miss creating a templates or pages with content.
Problem, if you create some pages local. Later I do a same if the page go live.

**Comment by tobias-kuendig** [comment]
@evwerkz Thank you for your feedback!

> I'm missing an upload form by repeater.

Box Config

```yaml
name: Repeater Example
handle: repeater-example
form:
  fields:
    extra_information:
        type: repeater
        form:
            fields:
                title:
                    label: title
                is_enabled:
                    label: Enabled
                    type: switch
                photos:
                    label: Photos
                    type: fileupload
                    mode: image
```

With Model

```php
<?php

namespace OFFLINE\Boxes\Models;

use October\Rain\Database\ExpandoModel;

class RepeaterItem extends ExpandoModel
{
    public $table = 'acme_blog_repeater_items';

    protected $expandoPassthru = ['parent_id'];

    public $attachMany = [
        'photos' => \System\Models\File::class,
    ];
}
```

And Provider

```php

        \OFFLINE\Boxes\Models\Box::extend(function ($model){
            $model->hasMany = [
                'extra_information' => [
                    RepeaterItem::class,
                    'key' => 'parent_id',
                    'delete' => true
                ],
            ];
        });
```

Works on my end:

```html
<div>
    {{ d(box.extra_information[0].photos) }}
</div>
```

What does not work for you?

> Settings to allow adding limited same box.

This is a very niche requirement and probably won't be added to the plugin.

>  Problem, if you create some pages local. Later I do a same if the page go live.

Page templates currently are not meant for this use-case. They provide simple starting points for creating new sites, but are not meant to transfer page data from one place to another.
