### DISCUSSION TITLE
Passing Dynamic Attributes to Component

### DISCUSSION THREAD

**Discussion by sqwk** [OFFLINE-GmbH/oc-boxes-support#111] [Help]
When using a component inside a box, I cannot pass any attributes to the component from the box:

```html
{% component 'renderForm' %}
```
```yaml
handle: form
name: Form
form:
    fields:
        form:
            label: Form
            type: text
components:
    renderForm:
        addToLayout: true
        properties:
            formCode: "{{box.form}}"
```

What is the suggested method to pass on form field to components?
