### DISCUSSION TITLE
Add description and icon in the box selector pop-up

### DISCUSSION THREAD

**Discussion by chocolata** [OFFLINE-GmbH/oc-boxes-support#158] [Ideas and feature requests]
Hi,

In the Box selection pop-up there are sections and labels, which is great. But could we expand this also with a bit more text and an icon?

![image](https://github.com/user-attachments/assets/06bf6425-280a-47d4-b005-f755afe5ee52)

I previously created a rudimentary pagebuilder within the Rainlab.Pages ecosystem, without preview function of course:

![image](https://github.com/user-attachments/assets/12ec01a4-6991-436d-92b5-4f50c57779e4)

My configuration yaml file looked like this:

```
banner:
    name: Banner
    description: Banner met rijke tekst
    icon: icon-align-left
    fields:
        content:
            label: Rijke tekst
            comment: Hiermee plaats je een rijke tekst in de banner
            type: richeditor
            span: full
        align:
            label: Uitlijning
            type: balloon-selector
            default: right
            options:
                left: Links
                center: Midden
                right: Rechts

```

There is an icon library present in the backend. Couldn't we make use of that?

If a site has many different boxes, it might be difficult for the user to differentiate between them...
