### DISCUSSION TITLE
Using component inside a partial from a plugin

### DISCUSSION THREAD

**Discussion by chrisvidal** [OFFLINE-GmbH/oc-boxes-support#169] [Help] [answered]
I am developing a plugin.
I want that plugin to hold all the boxes's partial and yaml files for easy updates if needed trough the plugin update.

no faq post are found nor displayed
the content is pulled from some Tailor content using the `collection` component similar to [there](https://github.com/OFFLINE-GmbH/oc-boxes-demo-partials/blob/main/themes/your-theme/partials/boxes/news.htm) 

but it looks like plugin and theme does not handle the boxes partial the same way.

Does it mean that i need to split my boxes partial inside the plugin for the one that wont be using any component and the theme for the ones that will be using components ?

What would be the recommendation here please ?

```yaml
name: FAQ
handle: faq
section: Component based

components:
    collection:
        component: faqs
        properties:
            handle: Content\FAQ
```

```twig
{% set latestPosts = faqs.limit(box.limit_posts | default(3)).get %}

<section class="block-faq">
  <div class="max-w-4xl mx-auto text-center">
    <h4 class="[text-wrap:balance]">{{ box.title }}</h4>
  </div>
  <div>
      {% for post in latestPosts %}
      <span>{{ post.question }}</span>
     {% endfor %}
   </div>

```

**Comment by tobias-kuendig** [comment]
Is your partial available in the backend? Can you add it to a site? If so, the registration is correct.

The component registration is the same for plugin and theme boxes.

If `{{ d(faqs) }}` in your partial returns something, everything is registered correctly, but your custom code/query may be wrong.

**Reply by chrisvidal** [reply]
yes the partial is in my plugin alongside with the yaml file in the backend side.

`{{ d(faqs) }}` returns `null`

do I need to add a `{% component 'faqs' %} ?

**Reply by tobias-kuendig** [reply]
No, the component should be registered automatically. 

Check here if your component is added: https://github.com/OFFLINE-GmbH/oc-boxes-free-plugin/blob/3f3916fa80c006b8fd78877de0739bae3292fd1d/classes/traits/HasBoxes.php#L150

I will see if I can reproduce the problem.

**Reply by chrisvidal** [reply, marked as answer]
ok I found the issue. it was not clear to me how to name the alias and the component itself.

so the correct `yaml` is 
```yaml
components:
    faqs:
        component: collection
        properties:
            handle: Content\FAQ
```

and not the other way around

```yaml
components:
    collection:
        component: faqs
        properties:
            handle: Content\FAQ
```
