### DISCUSSION TITLE
How do you render a mixin or use a mixin partial for it ?

### DISCUSSION THREAD

**Discussion by chrisvidal** [OFFLINE-GmbH/oc-boxes-support#170] [Help] [answered]
I have a standard button mixin

```yaml
handle: btn-mixin
mixin:
    button_text:
        label: boxes.button_text
        type: text
    button_href:
        label: boxes.button_href
        type: pagefinder
```

used inside another box as mixin

```yaml
btn-mixin:
   type: mixin
```

How can I have one partial to hold the html for this mixin that I could reuse in any box that would use it ?
