### DISCUSSION TITLE
Performance question

### DISCUSSION THREAD

**Discussion by chrisvidal** [OFFLINE-GmbH/oc-boxes-support#177] [Help]
I'm enabling debug bar and I see all this query which scares me in term of performance. 26 duplicate queries for my homepage for boxes plugin. How come ? What am I doing wrong ?

<img width="1497" alt="image" src="https://github.com/user-attachments/assets/7cc0b95a-0c3b-49da-8f38-5fa2c99ab85d" />

**Comment by chrisvidal** [comment]
another point performance wise, it looks like a component inserted inside a box is ran 3 times.

```yaml
# courses.yaml
name: Courses list
handle: component-courses
section: boxes.component
spacing:
- general
contexts:
    - container-children

components:
    courseList:

form:
    fields:
        title:
            label: boxes.title
            type: text
            default: Most popular courses
            example: Most popular courses
            tab: boxes.content
        limit_posts:
            label: Max. Number of courses to display
            type: number
            tab: boxes.content
            default: 3
```

inside `courses.htm`

```twig
{% component 'courseList' %}
```


and inside my component I have a simple

```php
public function onRun()
    {
        traceLog('run...');
}
```

that displays when i browse the box page. I am not rendering the boxe page my self, i let Boxes do everything.

```
[2024-12-14 10:45:24] local.INFO: run...  
[2024-12-14 10:45:24] local.INFO: run...  
[2024-12-14 10:45:24] local.INFO: run...  
```
