### DISCUSSION TITLE
Responsive Spacing

### DISCUSSION THREAD

**Discussion by chrisvidal** [OFFLINE-GmbH/oc-boxes-support#179] [Help]
How do you gys handle responsive spacing ?

Im using the spacing scale customized as pointed out [here](https://docs.boxes.offline.ch/use-cases/spacing.html#defining-the-scale) 
but i 'd like to be able to define specifically different spacing for mobile and desktop.

**Comment by tobias-kuendig** [comment]
You can just use media queries:

```css
.oc-boxes-spacing--before-small {
    margin-top: 1rem;
}

@media (min-width: 400px) {
    .oc-boxes-spacing--before-small {
        margin-top: 2rem;
    }
}
```

Or if you use Tailwind, you can use the Tailwind classes directly as before/after class `mt-4 md:mt-8`
