### DISCUSSION TITLE
Accessing model data from a box template

### DISCUSSION THREAD

**Discussion by adrian-stein** [OFFLINE-GmbH/oc-boxes-support#210] [Help] [answered]
I have a template set up as below and I want to access my custom model's data from my box. See below for heading and sub_heading where I try and use context.model. I know inside the partial I can use `{% set relatedModel = context.model.content %}` but can I access that same data so my preview looks correct when setting up box? I dont want to use the relatedModel code in the box partial as sometimes the box will be locked and sometime the user can add it and set the content themselves and adding relatedModel will break it.

```
templates:
    -   name: Blog
        handle: blog
        contexts:
            - blog
        boxes:
            - partial: header_page
              locked: true
              data:
                  heading: context.model.title
                  sub_heading: context.model.tag_line
```
