### DISCUSSION TITLE
Overriding mixins

### DISCUSSION THREAD

**Discussion by adrian-stein** [OFFLINE-GmbH/oc-boxes-support#220] [Ideas and feature requests]
The mixins are brilliant for reusable fields but there is the occasion when I want the mixin but want to change 1 property on it. For example have all the same data but put it on a different tab. It would be cool if the mixin copies over all the properties but if one existed on the parent then it used that instead of the default. For example I call my mixin for heading and its placed on the Content tab most times but for one place I want the tab to be Override.

```
heading:
    label: 'Heading'
    type: text
    span: full
    tab: 'Content'
```

```            
heading:
  type: mixin
  tab: 'Override'
```
