### DISCUSSION TITLE
Faker example content for richeditors

### DISCUSSION THREAD

**Discussion by adrian-stein** [OFFLINE-GmbH/oc-boxes-support#221] [Help]
I can use faker without issue for textareas and text boxes but for some reason it doesn't work for richeditor. Should it or am I doing something wrong? The below just return 'Copy' as my placeholder text which is the expected fallback.

```
  copy:
      label: 'Copy'
      type: richeditor
      span: full
      tab: 'Content'
      example:
          fake: paragraphs
          args: [2]
```
