### DISCUSSION TITLE
Displaying a custom project model data using a boxe page template ?

### DISCUSSION THREAD

**Discussion by chrisvidal** [OFFLINE-GmbH/oc-boxes-support#227] [Help]
Im using a custom plugin and want to set up a boxe page to handle the display of a project model with 3 partials: hero, actual project content and cta.

is this possible to handle with boxePage?

so far, I haven't find a way to.

I defined a boxe template, I created a boxPage with that template. then I created a Project CMS page with a standard url such as `/project/:slug` and then render the boxePage as shown in the doc.

All I got a 404 error with no error log with url like `http://oc-tll.test/project/project-title-1`

the boxe template:
```yaml
templates:
-   name: Project details
    handle: project
    boxes:
    - partial: hero-left
      locked: ['position', 'deletion']
    - partial: component-project
      locked: ['position', 'deletion']
    - partial: content-create-project
      locked: ['position', 'deletion']
      data: # Use the data property to define default values for the Box.
          title: Want to work together on this project?
          text: All good things starts with a collaboration.

```

the partial `component-project` holds the `projectDetails` component form my custom plugin

the project CMS page:

```twig
url = "/project/:slug"
layout = "default"
title = "Project details page"

[projectDetails]
slug = "{{ :slug }}"

[boxesPage boxesProject]
slug = "project"
modelType = "\Voilaah\Tll\Models\Project"

[resources]
vars[activeNavLink] = "projects"
==
{% component 'boxesProject' %}

```

what am I missing here please ?
