### DISCUSSION TITLE
Prefill page URL field from page name

### DISCUSSION THREAD

**Discussion by adrian-stein** [OFFLINE-GmbH/oc-boxes-support#232] [Ideas and feature requests]
Im adding lots of pages and I have to copy the page name into the URL field each time and then format it to remove spaces etc. It would be good if by default (or some config option) to allow the URL field to auto populate from the name field and format it as a slug. Like you can do on text boxes in October with the below code. It would save so much time when adding pages especially when you first create a site map for a site.

```
        name:
            label: name
            span: auto
            type: text
        slug:
            label: Slug
            span: auto
            defaultFrom: name
            preset:
                field: name
                type: slug
            type: text
```
