### DISCUSSION TITLE
Limit the catalog of children boxes

### DISCUSSION THREAD

**Discussion by CarolinePublipresse** [OFFLINE-GmbH/oc-boxes-support#50] [Ideas and feature requests]
Hello, 
Your module is great. Althought, I'm working on a website on witch the webdesigner has created some sections that are alike, but not exactly the same. I thought I could use nested boxes to work with this : 
I would like to set a parent box, with the common elements, and then propose to add some child boxes when needed, but only one or two that would be predefined, and not usable elsewhere as standalone. 

Exemple : 
On that case I need to add a button,
![image](https://user-images.githubusercontent.com/84564072/220414114-6d894533-47bb-454b-b8e2-6ff2abf967ff.png)

On this case I would like to add a child box with a repeater to create cards
![image](https://user-images.githubusercontent.com/84564072/220414319-a7b1e7e6-fe63-4c9a-b23d-d8e0963179f1.png)

As the box fields are opened on a sidebar, it is not always easy to visually separate clearly the elements. I would have liked to propose the cards as a child box to separate clearky the fieldgroups. But I don't want my client to add any other element in that place. 

Would it be possible ? 
Thanks.

**Comment by tobias-kuendig** [comment]
Thank you for this input,  @CarolinePublipresse. This was actually a feature that was already half implemented, as I previously had the need for it. I took your post as a good reason to finish it.

You can update to version `v2.1.41` and then specify specific `contexts` as `children`. This will then only display the partials with the specified contexts in the selector, when adding a new child.

Docs: https://docs.boxes.offline.ch/use-cases/nested-boxes.html#allow-only-specific-boxes-to-be-added-as-children

Let me know if you need any help.

**Reply by CarolinePublipresse** [reply]
Great ! So soon, thank you very much !

**Comment by CarolinePublipresse** [comment]
I tried to test it this morning, but I can't get the child to appear in the boxes list : 

The child :
```
# btn.yaml
handle: btn
name: Bouton
icon: /themes/lafrontaliere/assets/boxes/btn.png
contexts: 
- header-hp # this box is only available in as children of the "header-hp" box
form:
    fields:
        titre:
            label: Titre
            type: text
            comment: Ex. Configurer votre offre, J'obtiens mon tarif
            default: J'obtiens mon tarif
```

the parent : 
```
# header-hp.yaml
handle: header-hp
name: Entête Titre, texte, bouton, image
icon: /themes/lafrontaliere/assets/boxes/header-hp.png
children:
- btn
form:
    tabs:
        fields:
            titre:
                label: Titre
                type: text
                comment: mettre entre ** les termes à mettre en vert. Ex. **La frontalière santé**
                tab: Général
```

So, the chid has well disappeared from the global boxes list, and I have the link in the parent box to add children. But that children boxes list is empty. 

I don't know what I'm doing wrong...

**Reply by tobias-kuendig** [reply]
The parent needs to specify which child _contexts_ are available, not which _partials_. Since your context is named `header-hp` you need to specify that. It is important to note, that the contexts can be anything you want and are not related to the partial's handle.

This should work:

```yaml
# header-hp.yaml
handle: header-hp
name: Entête Titre, texte, bouton, image
icon: /themes/lafrontaliere/assets/boxes/header-hp.png
children:
- header-hp
# ...
```

Or alternatively named:

```yaml
# btn.yaml
handle: btn
name: Bouton
icon: /themes/lafrontaliere/assets/boxes/btn.png
contexts: 
- header-children # this box is only available in as children of the "header-hp" box
```

and

```yaml
# header-hp.yaml
handle: header-hp
name: Entête Titre, texte, bouton, image
icon: /themes/lafrontaliere/assets/boxes/header-hp.png
children:
- header-children
```
