### ISSUE TITLE
Image (fileupload relation) defined as required don't pass the validation:

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#10]
**Describe the bug**
When you add a fileupload field to your box (fe: image) and define it as required, you can't validate your box, it says "image is required" even if filled.

**To Reproduce**
1. Create a box with an image field             
            images:
                label: Images
                type: fileupload
                mode: image
2. Make that image as required
          validation:
              rules:
                  image:
                  - required
3. Add that box to your page, fill the image field
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/55833027/188827721-5ad7e73b-7b11-4354-85d2-b132c1016b3f.png)

**Comment by tobias-kuendig** [comment]
This seems to be no longer a problem. Validated that everything is working as expected with this yaml:

```yaml
name: Example
handle: example
validation:
    rules:
        image:
            - required
form:
  fields:
    image:
        label: Image
        type: fileupload
        mode: image
```
