### ISSUE TITLE
Update model fields partial paths: for Version 3.6

### ISSUE THREAD

**Issue by evwerkz** [OFFLINE-GmbH/oc-boxes-support#109]
Error by Pro Features:
![image](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/49227960/3a39ef87-50bf-40af-b468-fc3d96bcda77)

New Doc about partials: https://docs.octobercms.com/3.x/element/lists/column-partial.html

I'm testing with:

```
    published_by:
        label: 'offline.boxes::lang.published_by_short'
        type: partial
        path: published_by
```

and 

```
    revisions:
            type: partial
            tab: 'offline.boxes::lang.revisions'
            path: revisions
```

and now works fine.
