### ISSUE TITLE
Images disappear after submit within repeater field 

### ISSUE THREAD

**Issue by timbradson** [OFFLINE-GmbH/oc-boxes-support#126]
**Describe the bug**
I have created a repeater field where an image can also be uploaded. However after saving, the image is not saved and the field becomes blank again. This does not happen with other fields, which are saved correctly.

**Boxes Version**
v3.6.10

**To Reproduce**
1. Create a box with repeater field and add a fileupload widget 
2. Upload a media file
3. Save your box
4. Edit your box again, the image field is empty.

**Code**

```
name: Reviews 
handle: po\reviews
section: Reviews
form:
  fields:
    title_reviews:
      label: Title
      type: text
    reviews:
      label: Reviews
      prompt: Add new review
      type: repeater
      form:
        fields:
          text:
            label: Review Text
            type: textarea
            size: large
          image:
            label: Image
            type: fileupload
            mode: image
          name:
            label: Name
            type: text
          subname:
            label: Subtitle
            type: text
```

**Screenshots**
**Image disappear after clicking save**
![CleanShot 2024-05-10 at 23 55 40](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/25516702/769eb92c-a19c-4435-9d91-0e74ab05c63a)

**Image cannot be loaded into the front-end**
![Scherm­afbeelding 2024-05-10 om 23 56 41](https://github.com/OFFLINE-GmbH/oc-boxes-support/assets/25516702/425fb735-c772-4443-a023-78a184c94f6f)
