### ISSUE TITLE
Validate Repeater

### ISSUE THREAD

**Issue by sqwk** [OFFLINE-GmbH/oc-boxes-support#131]
How can I validate fields inside a repeater?

```
handle: faq
name: FAQ with Sidebar
labelFrom: title
form:
    fields:
        title:
            label: Title
            type: text
            default: FAQ
            required: true
        faq:
            label: FAQs
            type: repeater
            titleFrom: title
            minItems: 1
            form:
                fields:
                    title:
                        label: Title
                        type: text
                        required: true
                    text:
                        label: Content
                        type: richeditor
                        required: true
validation:
    rules:
        title:
            - required
        faq.title:
            - required
        faq.text:
            - required
```

Using dot notation as `faq.title`or `faq.*.title` does not work. In vanilla October one would extend the beforeValidate method inside the model — can something similar be achieved using Boxes?

**Comment by patrick-durrer** [comment]
If you want to validate a repeater, you will need the array validation syntax: https://laravel.com/docs/11.x/validation#validating-arrays

So in your case:

```yaml
validation:
    rules:
        faq.*.title:
            - required
```
The asterisk is the wildcard for the array key.
