### ISSUE TITLE
Dynamic Labels Do Not Default to Name When Field Is Empty

### ISSUE THREAD

**Issue by sqwk** [OFFLINE-GmbH/oc-boxes-support#133]
The following code does not default to `Title & Text `when the `title` field is empty. (like described on https://docs.boxes.offline.ch/concepts/box-configs.html)

```
handle: title-text
name: Title & Text
labelFrom: title
form:
    fields:
        title:
            label: Title
            type: text
```

Boxes v3.6.14 on October v3.6.24.
