### ISSUE TITLE
Repeater Items parent_id is lost on update

### ISSUE THREAD

**Issue by cezard** [OFFLINE-GmbH/oc-boxes-support#160]
**Describe the bug**
I am trying to use a RepeaterItem field for a Box. The form renders fine, and you can add items as expected and they save correctly. The problem is that on first update, all previously saved repeater items loose their parent_id in the database (it becomes NULL). 

**Boxes Version**
v3.6.32

**To Reproduce**
1. Add a new Box to a Page
2. Add a new Item in the Box
3. Save the page and refresh the page (everything looks good)
4. Save the page a second time and all the Items disappear

**Code**
My box config looks like this:

```
handle: boxes-fb
name: Featured blocks
section: Sections
form:
    fields:
      blocks:
        type: repeater
        label: Item
        itemsExpanded: false
        titleFrom: title
        form:
          fields:
            title:
                label: Title
                type: text
            text:
                label: Text
                type: textarea
            link_text:
                label: Link text
                type: text
            link_href:
                label: Link url
                type: text
            background:
                label: Background
                type: fileupload
                mode: image
            background_alt:
                type: text
                label: "Background alt"
                span: auto
```

My App\Provider.php looks like this: 
```
        \OFFLINE\Boxes\Models\Box::extend(function (\OFFLINE\Boxes\Models\Box $box) {

            $box->hasMany['blocks'] = [
                \OFFLINE\Boxes\Models\RepeaterItem::class,
                'key' => 'parent_id',
                'delete' => true,
            ];

        });

        \OFFLINE\Boxes\Models\RepeaterItem::extend(function (\OFFLINE\Boxes\Models\RepeaterItem $repeater) {
            $repeater->attachOne['icon'] = \System\Models\File::class;
            $repeater->attachOne['background'] = \System\Models\File::class;
            $repeater->attachOne['file'] = \System\Models\File::class;
        });
```

**Screenshots**
Add new Item
![image](https://github.com/user-attachments/assets/e8188f27-40cc-4212-a8e6-109a31f13293)
![image](https://github.com/user-attachments/assets/e93b81f0-f7e7-4456-8835-5558bfa0eb12)

Save Box
![image](https://github.com/user-attachments/assets/fa34af60-b789-4cd2-9b26-1002122e6b45)

Save Box a second time
![image](https://github.com/user-attachments/assets/69138f73-5480-41af-a87c-1dccdd323cde)

Database looks like this: 
![image](https://github.com/user-attachments/assets/b21fdadb-9209-4caf-ab65-8f6c00edc902)

**Additional context**
