### ISSUE TITLE
Page template feature stopped working

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#167]
**Describe the bug**
I defined some templates in my boxes.yaml file (littéral copied the documentation yaml to test), but when I create a new box page, I don't have any dropdown to select the template.

**Boxes Version**
v3.6.37

```yaml
    # /themes/your-theme/boxes.yaml
    templates:
    -   name: Empty page
        handle: empty
        boxes: []
    
    # A product page, the "hero" cannot be modified at all,
    # the "intro" is locked in-place, but the data is
    # modifiable by the user, see "Locking" below.
    -   name: Product page
        handle: product
        boxes:
        - partial: hero
          locked: true
        - partial: intro
          locked: ['position', 'deletion']
          data: # Use the data property to define default values for the Box.
              title: Default Title
              text: Default Text
        - partial: text
        - partial: container
          children: # nested boxes are supported as well.
            - partial: hero
            - partial: text
    
    
    # This template has a special "context" defined. This means
    # it will not be available in the Boxes Editor by default.
    -   name: Blog
        handle: blog
        contexts:
        - blog
        boxes:
        - partial: blog-hero
          locked: true
        - partial: blog-header
          locked: true
```
**Screenshots**
![image](https://github.com/user-attachments/assets/064ffa02-acf2-445b-a573-fef7dd2c7c4a)

**Additional context**
I'm in a multisite environment where each site have it's own theme that is child of a shared parent theme, don't know if it's important to precise
