### ISSUE TITLE
Is this a bug or limitation ?

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-boxes-support#180]
**Describe the bug**

```yaml
# slider.yaml
handle: content-slider
name: Slider
section: boxes.slider
...
form:
    name: Slider
    fields:
        slides:
            label: Slides
            type: repeater
            groups:
                text:
                    name: Text Slide
                    fields:
                        headline:
                            type: text
                image:
                    name: Image Slide
                    fields:
                        image:
                            type: fileupload
                        buttons:
                            type: repeater
                            prompt: add button
                            form:
                                fields:
                                    btn-mixin:
                                        type: mixin
```

** bug is located in these lines **

```yaml
 buttons:
                            type: repeater
                            prompt: add button
                            form:
                                fields:
                                    btn-mixin:
                                        type: mixin
```

**Boxes Version**
3.6.45

<img width="644" alt="image" src="https://github.com/user-attachments/assets/f2e900fa-3aa8-4fcd-bb8a-5fc55ae38f05" />

**Comment by tobias-kuendig** [comment]
v3.6.46 has now support for mixins in repeater groups, thanks @chrisvidal.

**Comment by chrisvidal** [comment]
thank you so much for your responsiveness @tobias-kuendig

**Comment by chrisvidal** [comment]
fileuplad images are not saved in the mixin apparently

**Comment by chrisvidal** [comment]
my config

```yaml
blocks:
                            label: Blocks
                            type: repeater
                            prompt: add new block
                            itemsExpanded: false
                            groups:
                                buttons:
                                    name: Buttons
                                    icon: icon-cube
                                    fields:
                                        buttons:
                                            type: repeater
                                            itemsExpanded: false
                                            form:
                                                fields:
                                                    btn-mixin:
                                                        type: mixin
                                images:
                                    name: Images
                                    icon: icon-cube
                                    fields:
                                        images:
                                            type: repeater
                                            itemsExpanded: false
                                            form:
                                                fields:
                                                    image_mixin:
                                                        type: mixin
```


```yaml
# _mixin_image
handle: image_mixin

mixin:
    image:
        label: boxes.img
        tab: boxes.image
        type: fileupload
        mode: image
        maxItems: 1
    img_text:
        label: boxes.img_text
        tab: boxes.image
        type: text
        comment: Your image SEO title
        span: full
    img_href:
        label: boxes.img_href
        tab: boxes.image
        type: pagefinder
        singleMode: true
        span: full
```

**Comment by tobias-kuendig** [comment]
Attachments in repeaters are not support in October out-of-the-box, so Boxes is no different.

You can use a repeater backed by a model to add support for file attachments. Boxes has some pre-defined for you to use (the repeater field has to be called `repeater_items` for it to work without additional config):
https://docs.boxes.offline.ch/use-cases/relations.html#repeater-relations-with-file-upload-support-since-v3-4

If you need more relations, you have to extend Boxes yourself, like documented here:
https://docs.octobercms.com/3.x/element/form/widget-repeater.html#example-of-using-related-records

**Comment by chrisvidal** [comment]
thanks for the explanation.

I did try following the example, the UI display accordingly but the record `new image` is not saved at all in the json

```yaml
                  repeater_items:
                            name: Images
                            label: Images
                            type: repeater
                            prompt: add new image
                            itemsExpanded: false
                            form:
                                fields:
                                    image_mixin:
                                        type: mixin

```
