### ISSUE TITLE
Reference box not rendering the assets

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-boxes-support#193]
**Describe the bug**
I have a box displaying and animating some stats number value in the about page.
Now, I am reusing this box as a reference inside the homepage.
but I noticed the number are not animated on this homepage.
After digging, I found out that the assets defined in the box were not loaded in the homepage

```
assets:
    js:
    -   name: /themes/demo/assets/js/boxes/anim-stats.js
        attributes:
            async: "async"
```

**Boxes Version**
v3.x.y
