### ISSUE TITLE
Can't access tailor model data in backoffice when boxes used as a field

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#196]
**Describe the bug**
This issue is related with this one #185 . I can access the tailor model using {{ context.model.content }} in front, but in backend, when I'm editing the model, it display null.

**Boxes Version**
v3.6.51

**Code**

My blog post model : 
```yml
uuid: 8d249dd5-af78-4184-a0eb-762c1fa30a6f
handle: Blog\Post
type: stream
name: Articles
drafts: false
showImport: false
showExport: false
multisite: true

primaryNavigation:
    label: Blog
    icon: ph ph-newspaper
    order: 900

navigation:
    parent: Blog\Post
    icon: ph ph-article
    order: 10

fields:
    tag:
        label: Tag
        validation: required
        type: entries
        source: Blog\Category
        maxItems: 1
        displayMode: relation
        tab: Infos
    date:
        label: Date
        type: datepicker
        mode: date
        default: now
        validation: required
        tab: Infos
    image:
        label: Image
        type: mediafinder
        maxItems: 1
        mode: image
        tab: Infos
    meta_title:
        label: Meta title
        type: text
        tab: Infos
    meta_description:
        label: Meta description
        type: textarea
        size: tiny
        tab: Infos
    boxes_content:
        label: Boxes Content
        tab: Contenu
        span: adaptive
        type: boxes
        template: blog
        previewLayout: default
        partialContexts:
            - blog
```

The code in my hero box : 

```
    {% set record = context.model.content %}
    {{ d(record) }}
```

**Screenshots**
Screenshot of the dump in front : 

![Image](https://github.com/user-attachments/assets/1b00349b-a168-46b8-8c2f-96feafcbb03f)

Screenshot of the dump in backoffice

![Image](https://github.com/user-attachments/assets/4c1ef43b-aade-4b48-bb0a-3d91d845a3b3)

Thank you
