### ISSUE TITLE
{{ record.boxes_content.render() | raw }} stopped working

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-boxes-support#205]
**Describe the bug**
I have a tailor model that use boxes as a field to fill content.

**Boxes Version**
v3.6.59

**To Reproduce**
1. Create a tailor model, add boxes to it using this : 

```yaml
      boxes_content:
          label: Boxes Content
          tab: Contenu
          span: adaptive
          type: boxes
          context: update
          template: blog
          previewLayout: default
          partialContexts:
              - blog
```

2. Create an october page to display model content, put that in your page markup
    {{ record.boxes_content.render() | raw }}

3. Create some content, go to see results in frontend, you will see an empty page.

Thank you

PS: It worked some weeks ago, and stopped working suddenly. (Probably due to a boxes updated as I regulary update it).
