### ISSUE TITLE
Multisite locale in combination with Rainlab Pages Menu

### ISSUE THREAD

**Issue by gldrenthe89** [OFFLINE-GmbH/oc-boxes-support#237]
**Describe the bug**
The latest version v3.6.77  (comming from 3.6.56) breaks the existing menu structure which is managed bij de Rainlab Pages plugin

**Boxes Version**
v3.6.77

**Code**
Menu yaml file contents: 
```yaml
items:
    -   title: Home
        nesting: 0
        type: offline-boxes-pages
        code: ''
        reference: home
        replace: 0
        viewBag:
            isHidden: '0'
            icon: ''
            cssClass: ''
            isExternal: '0'
            locale:
                de:
                    title: Startseite
name: 'Main menu'
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/fbb35010-dbc0-4929-95ad-5f0ca695369c)

**Additional context**
When l leave the menu empty the site works.
