### ISSUE TITLE
Box template with a box with children

### ISSUE THREAD

**Issue by mtareiling** [OFFLINE-GmbH/oc-boxes-support#79]
Is it possible to create a template with a box that has some standard children boxes?
Almost like a template in a template....
example:

```
-   name: columns
    handle: columns
    contexts:
    - page
    boxes:
    - partial: header
      locked: ['position', 'deletion']
    - partial: column-2
    data: header
```
