### ISSUE TITLE
When duplicating a page or exporting, children of other boxes are not exported

### ISSUE THREAD

**Issue by elisandroesp** [OFFLINE-GmbH/oc-boxes-support#86]
**Describe the bug**
When duplicating a page or exporting, only the first level of content is duplicated/exported, losing content

**Boxes Version**
v3.1.17

**To Reproduce**
1. Create a page (Page1) with a 'columns' component and add a couple children to this box
2. Duplicate the page
3. Go to the duplicated page (Page2)
4. See it only holds the 'columns' component, nothing inside it.

The same happens when you export this content, only the first level is exported.

**Code**
columns.yaml
```
handle: container-columns
name: Columns
section: Layout
children: true
spacing:
  - general

form:
  tabs:
    defaultTab: Content
    fields:

      columns:
        label: Number Of columns
        type: dropdown
        default: two
        options:
          one: 1
          two: 2
          three: 3
          four: 4

      anchors-mixin:
        type: mixin
```
columns.htm
```

<div
  class="
    bx--columns
    bx--columns--{{ box.columns }}
  "
  id="{{ box.anchor_id ? box.anchor_id : '' }}"
  data-boxes-container
>
    {% for child in box.children %}
        <div class="bx--columns__item">
            {{ child.renderMergeContext(context, { loop: loop, isChildren: true }) | raw }}
        </div>
    {% endfor %}
</div>

```
**Screenshots**

**Additional context**
WE LOVE Boxes!!!
